version: '3.8'

services:
  django:
    build: .
    image: django_server
    container_name: django_server
    expose:
      - "8000"
    environment:
      - PORT=8000
      - DATABASE_NAME=ai_dental_db
      - DATABASE_USER=ai_dental_user
      - DATABASE_PASSWORD=@squirtle1234#
      - DATABASE_HOST=postgres_db
      - DATABASE_PORT=5432
    volumes:
      - django_data:/home/appuser/AI_Dental_Health_APP/data/django
    depends_on:
      - postgres_db
    restart: always

  nginx:
    image: nginx:alpine
    container_name: nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - /etc/letsencrypt/live/dental-service.jieniguicare.org/fullchain.pem:/etc/letsencrypt/live/dental-service.jieniguicare.org/fullchain.pem:ro
      - /etc/letsencrypt/live/dental-service.jieniguicare.org/privkey.pem:/etc/letsencrypt/live/dental-service.jieniguicare.org/privkey.pem:ro
    depends_on:
      - django
    entrypoint: /bin/sh -c "nginx -g 'daemon off;'"
    restart: always

  postgres_db:
    image: postgres:13
    container_name: postgres_db
    environment:
      - POSTGRES_DB=ai_dental_db
      - POSTGRES_USER=ai_dental_user
      - POSTGRES_PASSWORD=@squirtle1234#
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    restart: always

volumes:
  django_data:
    driver: local
    driver_opts:
      type: "none"
      o: "bind"
      device: "/home/haoyu6875/docker_volumes/django_data"
  postgres_data:
    driver: local
    driver_opts:
      type: "none"
      o: "bind"
      device: "/home/haoyu6875/docker_volumes/postgres_data"