version: '3.8'

services:
  django:
    build: .
    image: ai_dental_health_app
    container_name: ai_dental_health_app
    expose:
      - "8000"
    environment:
      - PORT=8000
      - DATABASE_NAME=ai_dental_db
      - DATABASE_USER=ai_dental_user
      - DATABASE_PASSWORD=@squirtle1234#
      - DATABASE_HOST=postgres
      - DATABASE_PORT=5432
    volumes:
      - ./AI_Dental_Health_APP:/home/appuser/AI_Dental_Health_APP
    depends_on:
      - postgres
    restart: always

  nginx:
    image: nginx:alpine
    container_name: nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - /etc/letsencrypt/live/dental-service.jieniguicare.org/fullchain.pem:/etc/letsencrypt/live/dental-service.jieniguicare.org/fullchain.pem:ro
      - /etc/letsencrypt/live/dental-service.jieniguicare.org/privkey.pem:/etc/letsencrypt/live/dental-service.jieniguicare.org/privkey.pem:ro
    depends_on:
      - django
    entrypoint: /bin/sh -c "nginx -g 'daemon off;'"
    restart: always

  postgres:
    image: postgres:13
    container_name: postgres
    environment:
      - POSTGRES_DB=ai_dental_db
      - POSTGRES_USER=ai_dental_user
      - POSTGRES_PASSWORD=@squirtle1234#
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    ports:
      - "5432:5432"
    restart: always

volumes:
  AI_Dental_Health_APP:
  postgres_data: