version: '3.8'

services:
  django:
    build: .
    image: ai_dental_health_app
    container_name: ai_dental_health_app
    expose:
      - "8000"  # Exposing the internal port for Nginx to proxy
    environment:
      - PORT=8000
    volumes:
      - ./AI_Dental_Health_APP:/home/appuser/AI_Dental_Health_APP  # Mount the Django project to the host machine
    restart: always

  nginx:
    image: nginx:alpine
    container_name: nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./certbot/www:/var/www/certbot
      - ./certbot/conf:/etc/letsencrypt
    depends_on:
      - django
      - certbot
    entrypoint: /bin/sh -c "while [ ! -f /etc/letsencrypt/live/dental-service.jieniguicare.org/fullchain.pem ]; do sleep 1; done && nginx -g 'daemon off;'"
    restart: always

  certbot:
    image: certbot/certbot
    container_name: certbot
    volumes:
      - ./certbot/www:/var/www/certbot
      - ./certbot/conf:/etc/letsencrypt
    entrypoint: "/bin/sh -c 'trap exit TERM; certbot certonly --webroot --webroot-path=/var/www/certbot --email yy32438084@gmail.com --agree-tos --no-eff-email -d dental-service.jieniguicare.org; while :; do certbot renew; sleep 12h & wait $${!}; done;'"
    restart: always

volumes:
  AI_Dental_Health_APP: