version: '3.8'

services:
  django:
    build: .
    image: ai_dental_health_app
    container_name: ai_dental_health_app
    expose:
      - "8000"  # Exposing the internal port for Nginx to proxy
    environment:
      - PORT=8000
    volumes:
      - ./AI_Dental_Health_APP:/home/appuser/AI_Dental_Health_APP  # Mount the Django project to the host machine
    restart: always

  nginx:
    image: nginx:alpine
    container_name: nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - /etc/letsencrypt/live/dental-service.jieniguicare.org/fullchain.pem:/etc/letsencrypt/live/dental-service.jieniguicare.org/fullchain.pem:ro
      - /etc/letsencrypt/live/dental-service.jieniguicare.org/privkey.pem:/etc/letsencrypt/live/dental-service.jieniguicare.org/privkey.pem:ro
    depends_on:
      - django
    entrypoint: /bin/sh -c "nginx -g 'daemon off;'"
    restart: always

volumes:
  AI_Dental_Health_APP: