name: Build and Deploy to GCE

on:
  push:
    branches:
      - main

env:
  PROJECT_ID: mtk-genius-for-home # TODO: update Google Cloud project id
  GAR_NAME: github-actions # TODO: update Artifact Registry name
  GAR_LOCATION: asia-east1 # TODO: update Artifact Registry location
  SERVICE: ai-dental-health-app # Service name for tagging
  INSTANCE_NAME_PREFIX: ai-dental-health-app-instance- # Prefix for instance name
  ZONE: asia-east1-b # TODO: update GCE zone
  PORT: 8000 # Port to be used by Gunicorn

jobs:
  deploy:
    permissions:
      contents: 'read'
      id-token: 'write'

    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Google Auth
        id: auth
        uses: 'google-github-actions/auth@v2'
        with:
          credentials_json: '${{ secrets.GCP_KEY }}'

      - name: Docker Auth
        run: |
          gcloud auth configure-docker "${{ env.GAR_LOCATION }}-docker.pkg.dev"

      - name: Build and Push Container
        run: |
          IMAGE_TAG="${{ env.GAR_LOCATION }}-docker.pkg.dev/${{ env.PROJECT_ID }}/${{ env.GAR_NAME }}/${{ env.SERVICE }}:${{ github.sha }}"
          echo "Building Docker image with tag: $IMAGE_TAG"
          docker build -t "$IMAGE_TAG" ./
          echo "Pushing Docker image to Artifact Registry: $IMAGE_TAG"
          docker push "$IMAGE_TAG"

      - name: Generate Unique Instance Name
        run: echo "INSTANCE_NAME=${INSTANCE_NAME_PREFIX}${GITHUB_SHA::8}" >> $GITHUB_ENV

      - name: Create GCE Instance with Container
        run: |
          IMAGE_TAG="${{ env.GAR_LOCATION }}-docker.pkg.dev/${{ env.PROJECT_ID }}/${{ env.GAR_NAME }}/${{ env.SERVICE }}:${{ github.sha }}"
          echo "Creating GCE instance with container image: $IMAGE_TAG"
          gcloud compute instances create-with-container ${INSTANCE_NAME} \
            --zone=${ZONE} \
            --container-image=$IMAGE_TAG \
            --container-restart-policy=always \
            --scopes=https://www.googleapis.com/auth/cloud-platform \
            --tags=http-server \
            --metadata=google-logging-enabled=true \
            --container-env=PORT=${PORT} \
            --container-command="gunicorn" \
            --container-arg="--workers=3" \
            --container-arg="--bind" \
            --container-arg="0.0.0.0:${PORT}" \
            --container-arg="AI_Dental_Health_APP.wsgi:application"

      - name: Verify Deployment
        run: |
          echo "Verifying GCE instance deployment"
          gcloud compute instances describe ${INSTANCE_NAME} --zone=${ZONE}
